### ISSUE TITLE
Update file README.txt

### ISSUE THREAD

**Issue by ThanhTon115** [latbeo0/fast-delivery-application#55]
Cập nhật file README.txt hướng dẫn cách thực thi code, yêu cầu thư viện cần cài đặt

**Comment by latbeo0** [comment]
Cách thực thi code:
- Activity: Nhận resquest từ người dùng chuyển request đến Controller 
-Controller: Điều hướng dữ liệu bằng cách gọi dữ liệu từ database chuyển đến View 
-Activity: Show kết quả cho người dùng.

Examble: Login Google

-Tại Activity: Click Button Google -> startActiviti với data người dùng nhập vào và chuyển đến Controller
- Controller: Get thông tin người dùng từ google gọi database để lưu thông tin xuống database, sau đó trả kết quả cho Activity.
- Activity: show kết quả ra màng hình.


Các thư viện sử dụng:
    /* Room database */
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    /* Room database testing helper */
    testImplementation "androidx.room:room-testing:$room_version"

    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:27.1.0')

    // Declare the dependency for the Firebase Authentication library
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-auth:20.0.4'

    //Otp
    implementation 'com.github.aabhasr1:OtpView:1.0.6'

    implementation "androidx.browser:browser:1.3.0"

    // Also declare the dependency for the Google Play services library and specify its version
    implementation 'com.google.android.gms:play-services-auth:19.0.0'

    implementation 'com.facebook.android:facebook-android-sdk:[8,9)'
	/* Facebook*/
    implementation 'com.github.smarteist:autoimageslider:1.3.2-appcompat'
	
	/* Progressbar */
    implementation 'com.alespero:expandable-cardview:0.8'

    /* Progressbar */
    implementation 'com.kofigyan.stateprogressbar:stateprogressbar:1.0.0'

**Comment by latbeo0** [comment]
implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'com.diegodobelo.expandingview:expanding-view:0.9.4'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:18.1.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
